### PR TITLE
Create error.md

### PR DESCRIPTION
**Pull request by Rohit1415**
I have error starting this app 
I mail you for this error but you not responding so I have created this file to resolve this error 
this PR is only for solving Error

### CODE REVIEW

**Comment by ANURAG-PATHAK** [comment]
Contact me over LinkedIn or Twitter

**Comment by ANURAG-PATHAK** [comment]
> I have error starting this app I mail you for this error but you not responding so I have created this file to resolve this error this PR is only for solving Error

install ts-node globally, it will run

**Comment by Rohit1415** [comment]
i have already installed TS globally

**Comment by Rohit1415** [comment]
> Contact me over LinkedIn or Twitter



> > I have error starting this app I mail you for this error but you not responding so I have created this file to resolve this error this PR is only for solving Error
> 
> Install ts-node globally, it will run

Please share me you contact details 
i want to work with you in this project

**Comment by ANURAG-PATHAK** [comment]
Linkedin: https://www.linkedin.com/in/anuragpathak0/

**Pull request closed without merging**
